name = "mellowcatfe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93cceaf627b4324e477cd8a3a51acee57a4d469f44a0193d54e13677b80d1350"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
