import { FileDiff } from "https://esm.sh/@pierre/diffs@1.2.10?bundle";
let diffStyle="unified", files=[];
function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;");}
function themeType(){const a=document.documentElement.getAttribute("data-theme");if(a==="dark")return"dark";if(a==="light")return"light";return matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";}
function shells(){const m=document.getElementById("files-mount");m.innerHTML="";if(!files.length){m.innerHTML='<div class="empty">No file changes in this range.</div>';return;}files.forEach((f,i)=>{const el=document.createElement("div");el.className="file";const label=({M:"changed",A:"added",D:"deleted",R:"renamed"})[f.status]||"changed";const cls=f.status==="D"?"pill del":"pill";el.innerHTML=`<div class="file-head"><span class="chev" data-c="${i}">▾</span><span class="file-path">${esc(f.path)}</span><span class="file-badges"><span class="adddel"><span class="a">+${f.additions}</span> <span class="d">−${f.deletions}</span></span><span class="${cls}">${label}</span></span></div><div class="file-body" data-b="${i}"><div class="diff-mount" data-m="${i}"></div></div>`;m.appendChild(el);});m.querySelectorAll("[data-c]").forEach(c=>c.addEventListener("click",()=>{const i=c.getAttribute("data-c");m.querySelector(`[data-b="${i}"]`).classList.toggle("hidden");c.closest(".file-head").classList.toggle("collapsed");}));}
function render(){const o={theme:{light:"github-light",dark:"github-dark"},themeType:themeType(),overflow:"wrap",diffStyle};files.forEach((f,i)=>{const t=document.querySelector(`[data-m="${i}"]`);if(!t)return;t.innerHTML="";try{new FileDiff(o).render({containerWrapper:t,oldFile:{name:f.path,contents:f.old||""},newFile:{name:f.path,contents:f.new||""}});}catch(e){t.innerHTML=`<pre style="padding:12px;color:var(--danger-fg)">diff render failed: ${e}</pre>`;}});}
matchMedia("(prefers-color-scheme: dark)").addEventListener("change",render);
new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:["data-theme"]});
document.querySelectorAll("#styleToggle button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("#styleToggle button").forEach(x=>x.classList.remove("active"));b.classList.add("active");diffStyle=b.getAttribute("data-style");render();}));
document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));tab.classList.add("active");const t=document.querySelector(tab.getAttribute("data-target"));if(t)t.scrollIntoView({behavior:"smooth",block:"start"});}));
document.querySelectorAll(".body-toggle button").forEach(b=>b.addEventListener("click",()=>{const v=b.getAttribute("data-view");document.querySelectorAll(".body-toggle button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".body-view").forEach(el=>el.classList.toggle("hidden",el.getAttribute("data-view")!==v));}));
try{files=JSON.parse(document.getElementById("diffdata").textContent);shells();render();}catch(e){document.getElementById("files-mount").innerHTML=`<pre style="padding:12px;color:var(--danger-fg)">could not parse inlined diff data: ${e}</pre>`;}
